import { config } from 'dotenv'
import { initializeApp } from 'firebase/app'
import { getFirestore, collection, doc, setDoc, Timestamp } from 'firebase/firestore'

// 環境変数を読み込み
config({ path: '.env.local' })

// Firebase設定（環境変数から取得）
const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
}

const app = initializeApp(firebaseConfig)
const db = getFirestore(app)

// カテゴリマスターデータ
const categories = [
  {
    id: 'cooking',
    name: '料理・お菓子作り',
    description: '家庭料理から本格的なお菓子作りまで',
    icon: 'chef-hat',
    color: '#f97316',
    parentId: null,
    level: 0,
    sortOrder: 1,
    isActive: true,
    isPopular: true,
    skillCount: 0,
  },
  {
    id: 'gardening',
    name: '園芸・ガーデニング',
    description: '植物の育て方、庭づくりのコツ',
    icon: 'flower',
    color: '#22c55e',
    parentId: null,
    level: 0,
    sortOrder: 2,
    isActive: true,
    isPopular: true,
    skillCount: 0,
  },
  {
    id: 'handicraft',
    name: '手芸・裁縫',
    description: '編み物、刺繍、洋裁など',
    icon: 'scissors',
    color: '#ec4899',
    parentId: null,
    level: 0,
    sortOrder: 3,
    isActive: true,
    isPopular: true,
    skillCount: 0,
  },
  {
    id: 'music',
    name: '楽器演奏',
    description: 'ピアノ、ギター、歌など',
    icon: 'music',
    color: '#8b5cf6',
    parentId: null,
    level: 0,
    sortOrder: 4,
    isActive: true,
    isPopular: true,
    skillCount: 0,
  },
  {
    id: 'technology',
    name: 'パソコン・スマホ',
    description: 'デジタル機器の使い方',
    icon: 'smartphone',
    color: '#3b82f6',
    parentId: null,
    level: 0,
    sortOrder: 5,
    isActive: true,
    isPopular: true,
    skillCount: 0,
  },
  {
    id: 'language',
    name: '語学',
    description: '英語、中国語、韓国語など',
    icon: 'globe',
    color: '#06b6d4',
    parentId: null,
    level: 0,
    sortOrder: 6,
    isActive: true,
    isPopular: true,
    skillCount: 0,
  },
  {
    id: 'art',
    name: '書道・絵画',
    description: '書道、水彩画、油絵など',
    icon: 'palette',
    color: '#f59e0b',
    parentId: null,
    level: 0,
    sortOrder: 7,
    isActive: true,
    isPopular: true,
    skillCount: 0,
  },
  {
    id: 'health',
    name: '健康・体操',
    description: 'ヨガ、太極拳、ストレッチなど',
    icon: 'heart',
    color: '#ef4444',
    parentId: null,
    level: 0,
    sortOrder: 8,
    isActive: true,
    isPopular: true,
    skillCount: 0,
  },
  // 社会活動カテゴリー
  {
    id: 'work',
    name: '仕事',
    description: '短期・長期の仕事、アルバイト',
    icon: 'briefcase',
    color: '#2563eb',
    parentId: null,
    level: 0,
    sortOrder: 9,
    isActive: true,
    isPopular: true,
    skillCount: 0,
  },
  {
    id: 'help',
    name: 'お手伝い',
    description: '日常生活のお手伝い、サポート',
    icon: 'helping-hand',
    color: '#16a34a',
    parentId: null,
    level: 0,
    sortOrder: 10,
    isActive: true,
    isPopular: true,
    skillCount: 0,
  },
  {
    id: 'volunteer',
    name: 'ボランティア',
    description: '地域貢献、社会奉仕活動',
    icon: 'heart-handshake',
    color: '#dc2626',
    parentId: null,
    level: 0,
    sortOrder: 11,
    isActive: true,
    isPopular: true,
    skillCount: 0,
  },
  {
    id: 'seminar',
    name: '講演会・セミナー',
    description: '講演会、セミナー、勉強会',
    icon: 'presentation',
    color: '#eab308',
    parentId: null,
    level: 0,
    sortOrder: 12,
    isActive: true,
    isPopular: true,
    skillCount: 0,
  },
  {
    id: 'event',
    name: 'イベント',
    description: '文化イベント、交流会、催し物',
    icon: 'calendar-star',
    color: '#ea580c',
    parentId: null,
    level: 0,
    sortOrder: 13,
    isActive: true,
    isPopular: true,
    skillCount: 0,
  },
  {
    id: 'meeting',
    name: '集会',
    description: '住民集会、会議、相談会',
    icon: 'users',
    color: '#7c3aed',
    parentId: null,
    level: 0,
    sortOrder: 14,
    isActive: true,
    isPopular: true,
    skillCount: 0,
  },
]

// サンプルスキルデータ
const sampleSkills = [
  {
    id: 'skill-001',
    title: '初心者向け家庭料理教室',
    description: '基本的な家庭料理を一から丁寧にお教えします。包丁の使い方から始めて、煮物、炒め物、汁物の基本をマスターしましょう。',
    shortDescription: '基本的な家庭料理を一から丁寧にお教えします',
    category: 'cooking',
    subCategory: '家庭料理',
    tags: ['初心者歓迎', '基本料理', '和食'],
    teacherId: 'teacher-001',
    teacherName: '田中花子',
    teacherPhotoURL: null,
    teacherLocation: '東京都世田谷区',
    duration: 120,
    price: {
      amount: 3000,
      currency: 'JPY',
      unit: 'per_lesson',
    },
    location: {
      type: 'offline',
      address: '東京都世田谷区三軒茶屋',
      prefecture: '東京都',
      city: '世田谷区',
      area: '三軒茶屋',
    },
    maxStudents: 4,
    currentBookings: 0,
    availableSlots: [
      { dayOfWeek: 1, startTime: '10:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '10:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '10:00', endTime: '16:00', isAvailable: true },
    ],
    images: [],
    videoURL: null,
    rating: {
      average: 4.8,
      count: 12,
      distribution: { 5: 10, 4: 2, 3: 0, 2: 0, 1: 0 },
    },
    difficulty: 'beginner',
    targetAudience: ['料理初心者', '主婦・主夫', 'シニア'],
    requirements: ['エプロン', '筆記用具'],
    isActive: true,
    isApproved: true,
    viewCount: 156,
    favoriteCount: 23,
  },
  {
    id: 'skill-002',
    title: 'ベランダでできる野菜作り',
    description: 'マンションのベランダでも楽しめる野菜作りをお教えします。プランターの選び方から収穫まで、都市部での園芸のコツをお伝えします。',
    shortDescription: 'ベランダでも楽しめる野菜作りを教えます',
    category: 'gardening',
    subCategory: '野菜作り',
    tags: ['ベランダ菜園', '初心者OK', '都市園芸'],
    teacherId: 'teacher-002',
    teacherName: '佐藤緑',
    teacherPhotoURL: null,
    teacherLocation: '神奈川県横浜市',
    duration: 90,
    price: {
      amount: 2500,
      currency: 'JPY',
      unit: 'per_lesson',
    },
    location: {
      type: 'both',
      address: '神奈川県横浜市港北区',
      prefecture: '神奈川県',
      city: '横浜市',
      area: '港北区',
    },
    maxStudents: 3,
    currentBookings: 0,
    availableSlots: [
      { dayOfWeek: 0, startTime: '09:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 6, startTime: '09:00', endTime: '17:00', isAvailable: true },
    ],
    images: [],
    videoURL: null,
    rating: {
      average: 4.9,
      count: 8,
      distribution: { 5: 7, 4: 1, 3: 0, 2: 0, 1: 0 },
    },
    difficulty: 'beginner',
    targetAudience: ['園芸初心者', 'マンション住まい', '自然好き'],
    requirements: ['汚れても良い服装', '軍手'],
    isActive: true,
    isApproved: true,
    viewCount: 89,
    favoriteCount: 15,
  },
  // 社会活動サンプルデータ（豊中市）
  // 🔨仕事（青色）
  {
    id: 'work-001',
    title: '豊中市役所での短期事務補助',
    description: '豊中市役所での書類整理や窓口案内のお手伝いをしていただきます。市民サービス向上にご協力ください。',
    shortDescription: '市役所での事務補助業務',
    category: 'work',
    subCategory: '事務・オフィスワーク',
    tags: ['短期', '事務', '市役所'],
    teacherId: 'admin-001',
    teacherName: '豊中市役所',
    teacherPhotoURL: null,
    teacherLocation: '大阪府豊中市',
    duration: 480,
    price: { amount: 8000, currency: 'JPY', unit: 'per_day' },
    location: {
      type: 'offline',
      address: '大阪府豊中市中桜塚3丁目1番1号',
      prefecture: '大阪府',
      city: '豊中市',
      area: '中桜塚',
      coordinates: { lat: 34.7813, lng: 135.4696 }
    },
    maxStudents: 3,
    currentBookings: 1,
    images: [], videoURL: null,
    rating: { average: 4.1, count: 18, distribution: { 5: 7, 4: 8, 3: 3, 2: 0, 1: 0 } },
    difficulty: 'beginner',
    targetAudience: ['早起き得意', '体力に自信あり', 'コミュニケーション好き'],
    requirements: ['動きやすい服装', '元気なあいさつ'],
    isActive: true, isApproved: true, viewCount: 89, favoriteCount: 12,
  },
  {
    id: 'work-004',
    title: '千里中央公園での清掃スタッフ',
    description: '千里中央公園の清掃作業です。公園内のゴミ拾いや落ち葉掃きを行います。',
    shortDescription: '公園の清掃作業',
    category: 'work',
    subCategory: '販売・接客',
    tags: ['接客', '販売', 'シニア歓迎'],
    teacherId: 'company-001',
    teacherName: 'イオンモール豊中',
    teacherPhotoURL: null,
    teacherLocation: '大阪府豊中市',
    duration: 240,
    price: { amount: 4000, currency: 'JPY', unit: 'per_shift' },
    location: {
      type: 'offline',
      address: '大阪府豊中市上新田1丁目17番1号',
      prefecture: '大阪府',
      city: '豊中市',
      area: '上新田',
      coordinates: { lat: 34.7634, lng: 135.4889 }
    },
    maxStudents: 5,
    currentBookings: 2,
    availableSlots: [{ dayOfWeek: 6, startTime: '10:00', endTime: '18:00', isAvailable: true }],
    images: [], videoURL: null,
    rating: { average: 4.2, count: 15, distribution: { 5: 6, 4: 7, 3: 2, 2: 0, 1: 0 } },
    difficulty: 'beginner',
    targetAudience: ['接客経験者', 'シニア', '主婦・主夫'],
    requirements: ['制服貸与', '笑顔で接客'],
    isActive: true, isApproved: true, viewCount: 78, favoriteCount: 23,
  },
  // 🤝お手伝い（緑色）
  {
    id: 'help-001',
    title: '高齢者宅での家事お手伝い',
    description: '一人暮らしの高齢者宅での掃除、洗濯、買い物代行などの生活支援をお願いします。',
    shortDescription: '高齢者の日常生活サポート',
    category: 'help',
    subCategory: '家事代行',
    tags: ['高齢者支援', '家事', '生活支援'],
    teacherId: 'helper-001',
    teacherName: '豊中市社会福祉協議会',
    teacherPhotoURL: null,
    teacherLocation: '大阪府豊中市',
    duration: 120,
    price: { amount: 2000, currency: 'JPY', unit: 'per_session' },
    location: {
      type: 'offline',
      address: '大阪府豊中市岡上の町2丁目1番15号',
      prefecture: '大阪府',
      city: '豊中市',
      area: '岡上の町',
      coordinates: { lat: 34.7892, lng: 135.4612 }
    },
    maxStudents: 2,
    currentBookings: 0,
    availableSlots: [{ dayOfWeek: 2, startTime: '10:00', endTime: '16:00', isAvailable: true }],
    images: [], videoURL: null,
    rating: { average: 4.8, count: 12, distribution: { 5: 10, 4: 2, 3: 0, 2: 0, 1: 0 } },
    difficulty: 'beginner',
    targetAudience: ['介護経験者', '主婦・主夫', '地域貢献希望者'],
    requirements: ['身元保証', '健康診断書'],
    isActive: true, isApproved: true, viewCount: 67, favoriteCount: 18,
  },
  // ❤️ボランティア（赤色）
  {
    id: 'volunteer-001',
    title: '豊中市立図書館での読み聞かせボランティア',
    description: '子どもたちへの絵本の読み聞かせボランティアを募集しています。週1回、1時間程度の活動です。',
    shortDescription: '図書館での読み聞かせ活動',
    category: 'volunteer',
    subCategory: '教育支援',
    tags: ['読み聞かせ', '子ども', '図書館'],
    teacherId: 'library-001',
    teacherName: '豊中市立岡町図書館',
    teacherPhotoURL: null,
    teacherLocation: '大阪府豊中市',
    duration: 60,
    price: { amount: 0, currency: 'JPY', unit: 'volunteer' },
    location: {
      type: 'offline',
      address: '大阪府豊中市岡町北3丁目4番2号',
      prefecture: '大阪府',
      city: '豊中市',
      area: '岡町北',
      coordinates: { lat: 34.7756, lng: 135.4523 }
    },
    maxStudents: 3,
    currentBookings: 1,
    availableSlots: [{ dayOfWeek: 0, startTime: '14:00', endTime: '15:00', isAvailable: true }],
    images: [], videoURL: null,
    rating: { average: 4.9, count: 25, distribution: { 5: 23, 4: 2, 3: 0, 2: 0, 1: 0 } },
    difficulty: 'beginner',
    targetAudience: ['子ども好き', '読書好き', 'シニア'],
    requirements: ['声の大きさ', '子どもへの愛情'],
    isActive: true, isApproved: true, viewCount: 134, favoriteCount: 45,
  },
  // 🎤講演会・セミナー（黄色）
  {
    id: 'seminar-001',
    title: 'シニア向けスマートフォン講座',
    description: '豊中市文化芸術センターでのシニア向けスマートフォン基本操作講座です。LINE、メール、カメラの使い方を学びます。',
    shortDescription: 'スマートフォンの基本操作講座',
    category: 'seminar',
    subCategory: 'デジタル講座',
    tags: ['スマートフォン', 'シニア', 'デジタル'],
    teacherId: 'instructor-001',
    teacherName: '豊中市文化芸術センター',
    teacherPhotoURL: null,
    teacherLocation: '大阪府豊中市',
    duration: 120,
    price: { amount: 1000, currency: 'JPY', unit: 'per_session' },
    location: {
      type: 'offline',
      address: '大阪府豊中市曽根東町3丁目7番2号',
      prefecture: '大阪府',
      city: '豊中市',
      area: '曽根東町',
      coordinates: { lat: 34.7567, lng: 135.4445 }
    },
    maxStudents: 20,
    currentBookings: 15,
    availableSlots: [{ dayOfWeek: 4, startTime: '13:30', endTime: '15:30', isAvailable: true }],
    images: [], videoURL: null,
    rating: { average: 4.6, count: 32, distribution: { 5: 18, 4: 12, 3: 2, 2: 0, 1: 0 } },
    difficulty: 'beginner',
    targetAudience: ['シニア', 'デジタル初心者', 'スマホ初心者'],
    requirements: ['スマートフォン持参', '筆記用具'],
    isActive: true, isApproved: true, viewCount: 189, favoriteCount: 56,
  },
  // 🎉イベント（オレンジ色）
  {
    id: 'event-001',
    title: '豊中まつり2024 ボランティアスタッフ募集',
    description: '豊中まつりでの会場設営、案内、清掃などのボランティアスタッフを募集しています。地域のお祭りを一緒に盛り上げましょう！',
    shortDescription: '豊中まつりのボランティア参加',
    category: 'event',
    subCategory: '地域イベント',
    tags: ['お祭り', 'ボランティア', '地域交流'],
    teacherId: 'festival-001',
    teacherName: '豊中まつり実行委員会',
    teacherPhotoURL: null,
    teacherLocation: '大阪府豊中市',
    duration: 480,
    price: { amount: 0, currency: 'JPY', unit: 'volunteer' },
    location: {
      type: 'offline',
      address: '大阪府豊中市豊南町東4丁目5番1号',
      prefecture: '大阪府',
      city: '豊中市',
      area: '豊南町東',
      coordinates: { lat: 34.7723, lng: 135.4789 }
    },
    maxStudents: 50,
    currentBookings: 23,
    availableSlots: [{ dayOfWeek: 6, startTime: '08:00', endTime: '18:00', isAvailable: true }],
    images: [], videoURL: null,
    rating: { average: 4.7, count: 67, distribution: { 5: 45, 4: 18, 3: 4, 2: 0, 1: 0 } },
    difficulty: 'beginner',
    targetAudience: ['地域住民', 'お祭り好き', '体力に自信のある方'],
    requirements: ['動きやすい服装', '帽子', '水分補給'],
    isActive: true, isApproved: true, viewCount: 234, favoriteCount: 78,
  },
  // 📣集会（紫色）
  {
    id: 'meeting-001',
    title: '豊中市防災講習会・住民説明会',
    description: '豊中市の防災対策について学び、地域の防災計画について話し合う住民説明会です。',
    shortDescription: '防災に関する住民説明会',
    category: 'meeting',
    subCategory: '住民説明会',
    tags: ['防災', '住民説明会', '地域安全'],
    teacherId: 'city-001',
    teacherName: '豊中市危機管理課',
    teacherPhotoURL: null,
    teacherLocation: '大阪府豊中市',
    duration: 90,
    price: { amount: 0, currency: 'JPY', unit: 'free' },
    location: {
      type: 'offline',
      address: '大阪府豊中市服部西町4丁目13番1号',
      prefecture: '大阪府',
      city: '豊中市',
      area: '服部西町',
      coordinates: { lat: 34.7445, lng: 135.4556 }
    },
    maxStudents: 100,
    currentBookings: 45,
    availableSlots: [{ dayOfWeek: 0, startTime: '10:00', endTime: '11:30', isAvailable: true }],
    images: [], videoURL: null,
    rating: { average: 4.3, count: 89, distribution: { 5: 35, 4: 40, 3: 12, 2: 2, 1: 0 } },
    difficulty: 'beginner',
    targetAudience: ['地域住民', '防災に関心のある方', 'シニア'],
    requirements: ['筆記用具', '身分証明書'],
    isActive: true, isApproved: true, viewCount: 156, favoriteCount: 34,
  },
  
  // 追加サンプルデータ（豊中市周辺）
  // 🔨仕事（青色）追加データ
  {
    id: 'work-003',
    title: '豊中駅周辺でのチラシ配布スタッフ',
    description: '豊中駅周辺でのチラシ配布作業です。朝の通勤時間帯に活動していただきます。',
    shortDescription: '駅周辺でのチラシ配布作業',
    category: 'work',
    subCategory: '広告・宣伝',
    tags: ['チラシ配布', '朝の時間', '短時間'],
    teacherId: 'company-002',
    teacherName: '地域広告企業',
    teacherPhotoURL: null,
    teacherLocation: '大阪府豊中市',
    duration: 120,
    price: { amount: 2500, currency: 'JPY', unit: 'per_session' },
    location: {
      type: 'offline',
      address: '大阪府豊中市本町1丁目1番1号',
      prefecture: '大阪府',
      city: '豊中市',
      area: '本町',
      coordinates: { lat: 34.7817, lng: 135.4689 }
    },
    maxStudents: 10,
    currentBookings: 3,
    availableSlots: [{ dayOfWeek: 1, startTime: '07:30', endTime: '09:30', isAvailable: true }],
    images: [], videoURL: null,
    rating: { average: 4.1, count: 18, distribution: { 5: 7, 4: 8, 3: 3, 2: 0, 1: 0 } },
    difficulty: 'beginner',
    targetAudience: ['早起き得意', '体力に自信あり', 'コミュニケーション好き'],
    requirements: ['動きやすい服装', '元気なあいさつ'],
    isActive: true, isApproved: true, viewCount: 89, favoriteCount: 12,
  },
  {
    id: 'work-004',
    title: '千里中央公園での清掃スタッフ',
    description: '千里中央公園の清掃作業です。公園内のゴミ拾いや落ち葉掃きを行います。',
    shortDescription: '公園の清掃作業',
    category: 'work',
    subCategory: '清掃・管理',
    tags: ['公園', '清掃', '屋外作業'],
    teacherId: 'park-001',
    teacherName: '豊中市公園緑地課',
    teacherPhotoURL: null,
    teacherLocation: '大阪府豊中市',
    duration: 180,
    price: { amount: 3500, currency: 'JPY', unit: 'per_session' },
    location: {
      type: 'offline',
      address: '大阪府豊中市新千里東町1丁目',
      prefecture: '大阪府',
      city: '豊中市',
      area: '新千里東町',
      coordinates: { lat: 34.7889, lng: 135.4778 }
    },
    maxStudents: 6,
    currentBookings: 2,
    availableSlots: [{ dayOfWeek: 3, startTime: '09:00', endTime: '12:00', isAvailable: true }],
    images: [], videoURL: null,
    rating: { average: 4.4, count: 22, distribution: { 5: 12, 4: 8, 3: 2, 2: 0, 1: 0 } },
    difficulty: 'beginner',
    targetAudience: ['屋外作業好き', '体力に自信あり', '環境意識高い'],
    requirements: ['作業用手袋', '水分補給', '帽子'],
    isActive: true, isApproved: true, viewCount: 134, favoriteCount: 28,
  },
  {
    id: 'help-002',
    title: '子育て中のお母さんのお買い物代行',
    description: '小さなお子さんがいて外出が困難なお母さんのお買い物を代行します。',
    shortDescription: '子育て中の方のお買い物サポート',
    category: 'help',
    subCategory: '買い物代行',
    tags: ['子育て支援', '買い物代行', '育児サポート'],
    teacherId: 'support-001',
    teacherName: '豊中子育てサポートセンター',
    teacherPhotoURL: null,
    teacherLocation: '大阪府豊中市',
    duration: 90,
    price: { amount: 1500, currency: 'JPY', unit: 'per_session' },
    location: {
      type: 'offline',
      address: '大阪府豊中市小曽根4丁目4番19号',
      prefecture: '大阪府',
      city: '豊中市',
      area: '小曽根',
      coordinates: { lat: 34.7534, lng: 135.4612 }
    },
    maxStudents: 3,
    currentBookings: 1,
    availableSlots: [{ dayOfWeek: 5, startTime: '10:00', endTime: '11:30', isAvailable: true }],
    images: [], videoURL: null,
    rating: { average: 4.8, count: 16, distribution: { 5: 13, 4: 3, 3: 0, 2: 0, 1: 0 } },
    difficulty: 'beginner',
    targetAudience: ['子育て経験者', '主婦・主夫', '地域貢献希望者'],
    requirements: ['身元保証', '車の運転免許'],
    isActive: true, isApproved: true, viewCount: 98, favoriteCount: 22,
  },
  {
    id: 'volunteer-002',
    title: '豊中市高齢者施設での話し相手ボランティア',
    description: '高齢者施設での入居者の方々との会話やレクリエーション活動のサポートをお願いします。',
    shortDescription: '高齢者施設での話し相手活動',
    category: 'volunteer',
    subCategory: '高齢者支援',
    tags: ['高齢者支援', '話し相手', 'レクリエーション'],
    teacherId: 'elderly-001',
    teacherName: '豊中市高齢者福祉施設',
    teacherPhotoURL: null,
    teacherLocation: '大阪府豊中市',
    duration: 120,
    price: { amount: 0, currency: 'JPY', unit: 'volunteer' },
    location: {
      type: 'offline',
      address: '大阪府豊中市上野西2丁目12番5号',
      prefecture: '大阪府',
      city: '豊中市',
      area: '上野西',
      coordinates: { lat: 34.7634, lng: 135.4567 }
    },
    maxStudents: 8,
    currentBookings: 3,
    availableSlots: [{ dayOfWeek: 2, startTime: '14:00', endTime: '16:00', isAvailable: true }],
    images: [], videoURL: null,
    rating: { average: 4.9, count: 34, distribution: { 5: 31, 4: 3, 3: 0, 2: 0, 1: 0 } },
    difficulty: 'beginner',
    targetAudience: ['高齢者好き', 'コミュニケーション好き', 'シニア'],
    requirements: ['健康診断書', '身元保証書'],
    isActive: true, isApproved: true, viewCount: 167, favoriteCount: 45,
  },
  {
    id: 'seminar-002',
    title: '豊中市民向け健康講座・体操教室',
    description: '豊中市保健所主催の健康講座です。簡単な体操やストレッチを学びます。',
    shortDescription: '市民向け健康・体操講座',
    category: 'seminar',
    subCategory: '健康講座',
    tags: ['健康', '体操', 'ストレッチ'],
    teacherId: 'health-001',
    teacherName: '豊中市保健所',
    teacherPhotoURL: null,
    teacherLocation: '大阪府豊中市',
    duration: 90,
    price: { amount: 500, currency: 'JPY', unit: 'per_session' },
    location: {
      type: 'offline',
      address: '大阪府豊中市中桜塚4丁目11番1号',
      prefecture: '大阪府',
      city: '豊中市',
      area: '中桜塚',
      coordinates: { lat: 34.7723, lng: 135.4612 }
    },
    maxStudents: 25,
    currentBookings: 18,
    availableSlots: [{ dayOfWeek: 3, startTime: '10:00', endTime: '11:30', isAvailable: true }],
    images: [], videoURL: null,
    rating: { average: 4.5, count: 42, distribution: { 5: 22, 4: 16, 3: 4, 2: 0, 1: 0 } },
    difficulty: 'beginner',
    targetAudience: ['健康意識高い', 'シニア', '運動不足解消希望'],
    requirements: ['動きやすい服装', 'タオル', '水分補給'],
    isActive: true, isApproved: true, viewCount: 203, favoriteCount: 67,
  },
  {
    id: 'event-002',
    title: '豊中芸能祭スタッフ募集',
    description: '豊中芸能祭での会場準備、受付、清掃などのスタッフを募集しています。',
    shortDescription: '芸能祭のスタッフ募集',
    category: 'event',
    subCategory: '文化イベント',
    tags: ['芸能祭', 'スタッフ', '文化イベント'],
    teacherId: 'culture-001',
    teacherName: '豊中市文化芸術センター',
    teacherPhotoURL: null,
    teacherLocation: '大阪府豊中市',
    duration: 300,
    price: { amount: 0, currency: 'JPY', unit: 'volunteer' },
    location: {
      type: 'offline',
      address: '大阪府豊中市曽根東町3丁目7番2号',
      prefecture: '大阪府',
      city: '豊中市',
      area: '曽根東町',
      coordinates: { lat: 34.7567, lng: 135.4445 }
    },
    maxStudents: 30,
    currentBookings: 12,
    availableSlots: [{ dayOfWeek: 0, startTime: '08:00', endTime: '18:00', isAvailable: true }],
    images: [], videoURL: null,
    rating: { average: 4.6, count: 28, distribution: { 5: 18, 4: 8, 3: 2, 2: 0, 1: 0 } },
    difficulty: 'beginner',
    targetAudience: ['文化イベント好き', 'コミュニケーション好き', '長時間作業可能'],
    requirements: ['動きやすい服装', 'スタッフバッジ着用'],
    isActive: true, isApproved: true, viewCount: 156, favoriteCount: 42,
  },
  {
    id: 'meeting-002',
    title: '豊中市都市計画住民説明会',
    description: '豊中市の都市計画に関する住民説明会です。地域の将来について話し合います。',
    shortDescription: '都市計画に関する住民説明会',
    category: 'meeting',
    subCategory: '都市計画',
    tags: ['都市計画', '住民説明会', '地域開発'],
    teacherId: 'city-002',
    teacherName: '豊中市都市計画課',
    teacherPhotoURL: null,
    teacherLocation: '大阪府豊中市',
    duration: 120,
    price: { amount: 0, currency: 'JPY', unit: 'free' },
    location: {
      type: 'offline',
      address: '大阪府豊中市中桁1丁目1番1号',
      prefecture: '大阪府',
      city: '豊中市',
      area: '中桁',
      coordinates: { lat: 34.7812, lng: 135.4678 }
    },
    maxStudents: 80,
    currentBookings: 35,
    availableSlots: [{ dayOfWeek: 6, startTime: '14:00', endTime: '16:00', isAvailable: true }],
    images: [], videoURL: null,
    rating: { average: 4.2, count: 56, distribution: { 5: 25, 4: 22, 3: 8, 2: 1, 1: 0 } },
    difficulty: 'beginner',
    targetAudience: ['地域住民', '都市計画関心者', '地域開発関心者'],
    requirements: ['特になし'],
    isActive: true, isApproved: true, viewCount: 189, favoriteCount: 34,
  },
  {
    id: 'help-003',
    title: 'ペットのお世話・散歩代行',
    description: '旅行や用事で家を空ける際のペットのお世話や散歩を代行します。',
    shortDescription: 'ペットのお世話サービス',
    category: 'help',
    subCategory: 'ペットケア',
    tags: ['ペット', '散歩代行', 'ペットシッター'],
    teacherId: 'pet-001',
    teacherName: '豊中ペットサポート',
    teacherPhotoURL: null,
    teacherLocation: '大阪府豊中市',
    duration: 60,
    price: { amount: 2000, currency: 'JPY', unit: 'per_session' },
    location: {
      type: 'offline',
      address: '大阪府豊中市南桃園町2丁目8番12号',
      prefecture: '大阪府',
      city: '豊中市',
      area: '南桃園町',
      coordinates: { lat: 34.7712, lng: 135.4823 }
    },
    maxStudents: 2,
    currentBookings: 0,
    availableSlots: [{ dayOfWeek: 6, startTime: '16:00', endTime: '17:00', isAvailable: true }],
    images: [], videoURL: null,
    rating: { average: 4.7, count: 24, distribution: { 5: 18, 4: 5, 3: 1, 2: 0, 1: 0 } },
    difficulty: 'beginner',
    targetAudience: ['動物好き', 'ペット飼育経験者', '責任感強い'],
    requirements: ['動物アレルギーなし', 'ペット飼育経験'],
    isActive: true, isApproved: true, viewCount: 145, favoriteCount: 38,
  },
  {
    id: 'work-005',
    title: '豊中市立病院での受付案内',
    description: '豊中市立病院での受付業務や患者さんの案内業務です。医療事務経験者歓迎。',
    shortDescription: '病院での受付・案内業務',
    category: 'work',
    subCategory: '医療事務',
    tags: ['病院', '受付', '患者案内'],
    teacherId: 'hospital-001',
    teacherName: '豊中市立病院',
    teacherPhotoURL: null,
    teacherLocation: '大阪府豊中市',
    duration: 240,
    price: { amount: 5000, currency: 'JPY', unit: 'per_shift' },
    location: {
      type: 'offline',
      address: '大阪府豊中市柿の木町4丁目7番1号',
      prefecture: '大阪府',
      city: '豊中市',
      area: '柿の木町',
      coordinates: { lat: 34.7623, lng: 135.4534 }
    },
    maxStudents: 4,
    currentBookings: 2,
    availableSlots: [{ dayOfWeek: 2, startTime: '08:30', endTime: '12:30', isAvailable: true }],
    images: [], videoURL: null,
    rating: { average: 4.6, count: 31, distribution: { 5: 18, 4: 11, 3: 2, 2: 0, 1: 0 } },
    difficulty: 'intermediate',
    targetAudience: ['医療事務経験者', 'コミュニケーション能力高い', '責任感強い'],
    requirements: ['医療事務経験', '身分証明書', '健康診断書'],
    isActive: true, isApproved: true, viewCount: 178, favoriteCount: 45,
  },
  {
    id: 'help-004',
    title: '高齢者向けPC・スマホサポート',
    description: '高齢者の方々のPCやスマートフォンの操作サポートを行います。ご自宅へ訪問します。',
    shortDescription: '高齢者向けデジタルサポート',
    category: 'help',
    subCategory: 'ITサポート',
    tags: ['高齢者支援', 'PCサポート', 'スマホ教室'],
    teacherId: 'it-001',
    teacherName: '豊中デジタルサポート',
    teacherPhotoURL: null,
    teacherLocation: '大阪府豊中市',
    duration: 90,
    price: { amount: 2500, currency: 'JPY', unit: 'per_session' },
    location: {
      type: 'offline',
      address: '大阪府豊中市山の上町1丁目15番3号',
      prefecture: '大阪府',
      city: '豊中市',
      area: '山の上町',
      coordinates: { lat: 34.7667, lng: 135.4445 }
    },
    maxStudents: 1,
    currentBookings: 0,
    availableSlots: [{ dayOfWeek: 4, startTime: '14:00', endTime: '15:30', isAvailable: true }],
    images: [], videoURL: null,
    rating: { average: 4.9, count: 27, distribution: { 5: 25, 4: 2, 3: 0, 2: 0, 1: 0 } },
    difficulty: 'beginner',
    targetAudience: ['ITスキルあり', '教えるのが好き', '忍耐強い'],
    requirements: ['ノートPC持参', '教えるスキル'],
    isActive: true, isApproved: true, viewCount: 189, favoriteCount: 52,
  },
  {
    id: 'volunteer-003',
    title: '豊中市環境清掃ボランティア',
    description: '豊中市内の公園や道路の清掃ボランティア活動です。地域の美化に貢献しましょう。',
    shortDescription: '環境清掃ボランティア活動',
    category: 'volunteer',
    subCategory: '環境保護',
    tags: ['環境保護', '清掃', '地域美化'],
    teacherId: 'env-001',
    teacherName: '豊中市環境部',
    teacherPhotoURL: null,
    teacherLocation: '大阪府豊中市',
    duration: 120,
    price: { amount: 0, currency: 'JPY', unit: 'volunteer' },
    location: {
      type: 'offline',
      address: '大阪府豊中市蛍池東町3丁目5番1号',
      prefecture: '大阪府',
      city: '豊中市',
      area: '蛍池東町',
      coordinates: { lat: 34.7889, lng: 135.4456 }
    },
    maxStudents: 15,
    currentBookings: 8,
    availableSlots: [{ dayOfWeek: 0, startTime: '09:00', endTime: '11:00', isAvailable: true }],
    images: [], videoURL: null,
    rating: { average: 4.4, count: 38, distribution: { 5: 20, 4: 14, 3: 4, 2: 0, 1: 0 } },
    difficulty: 'beginner',
    targetAudience: ['環境意識高い', '体力に自信あり', '地域貢献希望'],
    requirements: ['作業用手袋', '汚れても良い服装'],
    isActive: true, isApproved: true, viewCount: 167, favoriteCount: 43,
  },
]

async function seedFirestore() {
  try {
    console.log('🌱 Firestoreデータベースの初期化を開始します...')

    // カテゴリデータの投入
    console.log('📂 カテゴリデータを投入中...')
    for (const category of categories) {
      await setDoc(doc(db, 'categories', category.id), {
        ...category,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
      })
      console.log(`✅ カテゴリ「${category.name}」を作成しました`)
    }

    // サンプルスキルデータの投入
    console.log('🎯 サンプルスキルデータを投入中...')
    for (const skill of sampleSkills) {
      await setDoc(doc(db, 'skills', skill.id), {
        ...skill,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
      })
      console.log(`✅ スキル「${skill.title}」を作成しました`)
    }

    console.log('🎉 Firestoreデータベースの初期化が完了しました！')
    console.log(`📊 作成されたデータ:`)
    console.log(`   - カテゴリ: ${categories.length}件`)
    console.log(`   - スキル: ${sampleSkills.length}件`)

  } catch (error) {
    console.error('❌ データベース初期化中にエラーが発生しました:', error)
    process.exit(1)
  }
}

// スクリプト実行
if (require.main === module) {
  seedFirestore()
    .then(() => {
      console.log('✨ 初期化スクリプトが正常に完了しました')
      process.exit(0)
    })
    .catch((error) => {
      console.error('💥 スクリプト実行中にエラーが発生しました:', error)
      process.exit(1)
    })
}

export { seedFirestore }
